### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by mrtanloveoflife** [imixs/imixs-jsf-example#46]
Hi, when I accept the ticket from open status to in progress status a plugin error happens
![image](https://user-images.githubusercontent.com/36816355/67583836-95075c80-f776-11e9-93d2-447005a1ff02.png)

And this is what the log says:
![image](https://user-images.githubusercontent.com/36816355/67583900-b7997580-f776-11e9-81a5-f0dc8c748ec9.png)

How can i fix it? Thanks.

**Comment by rsoika** [comment]
Which version of imixs-workflow are you currently using? You can see this at to footer of your sample application. You should use 5.1.0

Have you any deployment errors? Are you running on Wildfly Docker image?

**Comment by mrtanloveoflife** [comment]
I use the latest release of Sample Application and it's using imixs-workflow Version 5.0.4, also I'm running it on Wildfly Docker image.

**Comment by rsoika** [comment]
Yes ,you are right, there was a bug in this release. The Demo class 'DemoAdapter' in this version need to extend the interface 'SignalAdapter' instead of 'Adapter' 

You can change the interface or you simply switch to the latest version of the imixs-jsf-example (master branch) were the bug is already fixed.

**Comment by mrtanloveoflife** [comment]
Your update works perfectly now, thank you!
